name: Compile

on:
  push:
    paths:
      - 'src/**'
      - 'Makefile'
      - '.github/workflows/compile.yml'
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile
        run: |
          echo "$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
          make

      - name: Uplaod
        uses: actions/upload-artifact@v4
        with:
          name: CVE-2022-38181
          path: build/shrinker
